Helm template update for repository
Qiskit-Extensions/quantum-serverless pull request #239
Opened 2023-02-27 20:50 UTC by akihikokuroda

### Summary
Fix #157

Add helm template for repository 

### Details and comments

2023-02-28 09:27 UTC, Tansito requested changes
Instead of adding templates directly how in the Helm we are managing different projects we decided to follow a [sub-charts architecture](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/). Could you create a sub-chart for `quantum-serverless` and `repository`? It should be something like:
```
$ cd quantumserverless/charts
$ helm create repository
Creating repository
```
Similar for what we have for `jupyter` and `manager`.

2023-02-28 13:51 UTC, akihikokuroda commented
@Tansito Thanks for review.  I'll move changes into the sub-chart.

2023-03-07 14:26 UTC, pacomf approved these changes

2023-03-08 16:02 UTC, Tansito approved these changes
Thanks for this @akihikokuroda ! I just proposed a little change but nothing problematic 👍

2023-03-08 18:42 UTC, akihikokuroda commented on infrastructure/helm/quantumserverless/charts/repository/Chart.yaml
> +description: A Helm chart for Kubernetes
Thanks! I fix it.

2023-03-09 10:04 UTC, merged